# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = "ï„ "
"kitty" = "ï„ "
"foot" = "ï„ "
"termit" = "ï„ "
"konsole" = "ï„ "
"terminal" = "ï„ "
"bash" = "ï„ "
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"discord" = "ï­®"
"bing" = "îœ€"
"nerd fonts" = "ï€±"
"firefox" = "ï‚¬"
"waterfox" = "ï‚¬"
"chrome" = "ï‚¬"
"vivaldi" = "ï‚¬"
"qutebrowser" = "ï‚¬"
"thunar" = "ï¼"
"pcmanfm" = "ï¼"
"caja" = "ï¼"
"nautilus" = "ï¼"
"dolphin" = "ï¼"
"dolph" = "ï¼"
"xarchiver" = "ï"
"engrampa" = "ï"
"file-roller" = "ï"
"nvim" = "îŸ…"
"vim" = "îŸ…"
"vimiv" = "ï€¾"
"imv" = "ï€¾"
"imp" = "ï€¾"
"mpv" = "ïœª"
"musikcube" = "ï€"
[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = true
